---
title: "Lab 05 - Multiple Linear Regression"
date: "2022-10-27"
format: 
  html:
    self-contained: true
    theme:
      - flatly
      - lab.scss
---

**Due:** 2022-11-02 at 11:59pm
**Turn your .html file in on Canvas**

# Getting started

Go to RStudio Pro and click:

**Step 1**. File \> New Project\
**Step 2**. "Version Control"\
**Step 3**. Git\
**Step 4**. Copy the following into the "Repository URL":

```{bash}
#| eval: false
https://github.com/sta-112-f22/lab-05-multiple-linear-regression.git
```

# Exercises

```{r}
#| include: false
library(tidyverse)
library(Stat2Data)
```

The `Diamonds` data set can be used to examine the predict a diamond's price using characteristics about the diamond. For this lab, you need to try to find the **best model** to predict the total price of a diamond. Here "best" is defined as a model that (1) meets the assumptions of multiple regression and (2) has a good model fit, as determined by the metrics we've learned so far. I want you to **show your work**. Your report should include:

1. A list of all models you attempted
2. Figures displaying the checks for the assumptions for multiple linear regression for the **final model you pick**
3. The equation for the **final model you pick**
4. The model metric for the final model you picked (and how it compared to the other models)


1. T